#!/usr/bin/perl

use strict;
use Parse::RecDescent;
use Parse::RecDescent::Walker;
use Java::Tree;
use Data::Dumper;

# Slurp the file
$/ = undef;
$_ = <>;

#$::RD_TRACE = 0; $::RD_HINT = 1; $::RD_WARN = 1;
# $::RD_AUTOSTUB = 1;

$Parse::RecDescent::skip = qr{ (?: \s+ | /\* (?: (?! \*/ ) . )*+ \*/ | // [^\n]*+\n )* }xs;
open GRAMMAR, "grammar";
my $grammar = <GRAMMAR>;
close GRAMMAR;

my $parser = new Parse::RecDescent($grammar) or die "Bad grammar!\n";
my $tree = $parser->compilation_unit(\$_);
if ($_ =~ /\S/ or not $tree) {
  print "UNPARSED: [$_]\n";
  exit 1;
}

my $cu = Parse::RecDescent::Walker->walk($tree, 'Java::Tree');

print Dumper($cu);
